name: Different step types

on: 
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello Pranav!"
    
  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello Pranav!")
        shell: python

  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: "Hello Pranav Swaroop"