name: jobs dependencies workflow

on:
  push:
    branches:
      - '**'

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "A job consists of one or more steps"
      - run: echo "which run sequentially within the same compute environment"

  job-2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Multiple jobs can run in parallel"

  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "Jobs can also depend on one another"

  job-4:
    runs-on: ubuntu-24.04
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "forms a DAG(directed acyclic graph)"