name: secrets and variables

on:
  workflow_dispatch:

jobs:
  stg-env:
    runs-on: ubuntu-24.04
    environment: stg
    env: 
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}

      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}

    steps:
      - name: Inspect values inside job
        run: |
          echo "repo secret: $EXAMPLE_REPOSITORY_SECRET"
          echo "repo variable: $EXAMPLE_REPOSITORY_VARIABLE"
          echo "env secret: $EXAMPLE_ENVIRONMENT_SECRET"
          echo "env variable: $EXMPLE_ENVIRONMENT_VARIABLE"

  prod-env:
    runs-on: ubuntu-24.04
    environment: prod
    env:
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}

      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}

    steps:
      - name: Inspect values inside job
        run: |
          echo "repo secret: $EXAMPLE_REPOSITORY_SECRET"
          echo "repo variable: $EXAMPLE_REPOSITORY_VARIABLE"
          echo "env secret: $EXAMPLE_ENVIRONMENT_SECRET"
          echo "env variable: $EXMPLE_ENVIRONMENT_VARIABLE"